"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";

import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { formatMoney } from "@/lib/format";
import { creditFromPlatform } from "@/lib/wallet/server";
import {
  TOPUP_MAX_MINOR,
  TOPUP_MIN_MINOR,
  type TopUpMethod,
  type TopUpState,
} from "@/lib/wallet/topup-state";

/**
 * Customer-funded top-ups, through a simulated gateway.
 *
 * Two steps on purpose, mirroring how a real provider works: create an intent,
 * then confirm it. A single action that took an amount and credited a balance
 * would be the same code with no audit trail and nowhere to put a decline — and
 * it would have to be thrown away when a real gateway lands, rather than having
 * its confirm step swapped.
 *
 * **This lets an untrusted party initiate a credit,** which is the whole point
 * and also the risk. Four things carry that:
 *
 *   1. Every attempt is a row in `wallet_topups`, including the failures, so a
 *      credit always has an intent behind it.
 *   2. The confirm step *claims* the row with a conditional update before it
 *      posts any money. A double-submit or a refreshed page finds nothing left to
 *      claim and credits nothing — the same trick `resolveDispute` uses with
 *      `.neq("status", "resolved")`.
 *   3. Amounts are bounded in this file and again by a check constraint.
 *   4. The customer never supplies the amount at confirm time. It is read back
 *      from the row, so tampering with the confirm payload cannot change what
 *      gets credited.
 *
 * When a real provider replaces this, `simulateGateway` is the only function
 * that goes; the intent row, the claim, and the ledger posting all stay.
 */

/* ── Shared ───────────────────────────────────────────────────────────────── */

const FAILED = (error: string): TopUpState => ({ error, intent: null, outcome: null });

const METHODS = ["card", "upi", "netbanking"] as const satisfies readonly TopUpMethod[];

/**
 * "500" / "500.50" → paise. Rejects a third decimal rather than rounding it,
 * matching `rupeesToPaise` in the booking actions.
 */
function rupeesToPaise(input: string): number | null {
  const trimmed = input.trim().replace(/^₹/, "").replace(/,/g, "");
  if (!/^\d+(\.\d{1,2})?$/.test(trimmed)) return null;
  return Math.round(Number(trimmed) * 100);
}

async function currentUser() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return user;
}

/* ── Step 1: the intent ───────────────────────────────────────────────────── */

const IntentSchema = z.object({
  amount: z.string().trim().min(1, "Enter an amount."),
  method: z.enum(METHODS),
  // Generated by the client, one per attempt. Not trusted for anything except
  // de-duplication, and the unique index is what actually enforces that.
  idempotencyKey: z.string().trim().min(8).max(100),
});

export async function createTopUpIntent(
  _prev: TopUpState,
  formData: FormData,
): Promise<TopUpState> {
  const parsed = IntentSchema.safeParse({
    amount: formData.get("amount"),
    method: formData.get("method"),
    idempotencyKey: formData.get("idempotencyKey"),
  });

  if (!parsed.success) {
    return FAILED(parsed.error.issues[0]?.message ?? "Check the amount and try again.");
  }

  const user = await currentUser();
  if (!user) return FAILED("Sign in to add funds.");

  const minor = rupeesToPaise(parsed.data.amount);
  if (minor === null) {
    return FAILED("Enter the amount in rupees, like 500 or 500.50.");
  }
  if (minor < TOPUP_MIN_MINOR) {
    return FAILED(`The smallest top-up is ${formatMoney(TOPUP_MIN_MINOR)}.`);
  }
  if (minor > TOPUP_MAX_MINOR) {
    return FAILED(`The largest single top-up is ${formatMoney(TOPUP_MAX_MINOR)}.`);
  }

  const admin = createAdminClient();

  const { data, error } = await admin
    .from("wallet_topups")
    .insert({
      user_id: user.id,
      amount_minor: minor,
      method: parsed.data.method,
      idempotency_key: parsed.data.idempotencyKey,
    })
    .select("reference, amount_minor, method")
    .maybeSingle<{ reference: string; amount_minor: number; method: TopUpMethod }>();

  if (error) {
    // A repeated key means the customer already started this exact attempt —
    // most likely a double-click. Recover by handing back the existing intent
    // rather than refusing, so they land on the gateway either way.
    if (error.code === "23505") {
      const { data: existing } = await admin
        .from("wallet_topups")
        .select("reference, amount_minor, method, status")
        .eq("user_id", user.id)
        .eq("idempotency_key", parsed.data.idempotencyKey)
        .maybeSingle<{
          reference: string;
          amount_minor: number;
          method: TopUpMethod;
          status: string;
        }>();

      if (existing && existing.status === "pending") {
        return {
          error: null,
          intent: {
            reference: existing.reference,
            amountMinor: existing.amount_minor,
            method: existing.method,
          },
          outcome: null,
        };
      }

      return FAILED("That payment has already been processed. Refresh to see your balance.");
    }

    console.error("[topup] intent creation failed", {
      code: error.code,
      message: error.message,
    });

    if (error.code === "42P01" || error.code === "PGRST205") {
      return FAILED("Top-ups are not set up on this database yet.");
    }
    return FAILED("That payment could not be started. Try again in a moment.");
  }

  if (!data) return FAILED("That payment could not be started. Try again in a moment.");

  return {
    error: null,
    intent: {
      reference: data.reference,
      amountMinor: data.amount_minor,
      method: data.method,
    },
    outcome: null,
  };
}

/* ── The simulated gateway ────────────────────────────────────────────────── */

/**
 * Stands in for a payment provider. Deterministic, so the decline path is
 * testable without waiting for a real bank to refuse something.
 *
 *   • card       — declines when the number ends in `0000`
 *   • upi        — declines when the id begins `fail@`
 *   • netbanking — always succeeds; there is no credential to get wrong
 *
 * These rules are shown in the UI. That is deliberate: it is a mock, and hiding
 * how to trigger a failure would make the failure path untestable by anyone but
 * whoever wrote it.
 */
function simulateGateway(
  method: TopUpMethod,
  credential: string,
): { ok: true } | { ok: false; reason: string } {
  const value = credential.trim();

  if (method === "card") {
    const digits = value.replace(/\s+/g, "");
    if (!/^\d{16}$/.test(digits)) {
      return { ok: false, reason: "That card number is not 16 digits." };
    }
    if (digits.endsWith("0000")) {
      return { ok: false, reason: "Your bank declined that card." };
    }
    return { ok: true };
  }

  if (method === "upi") {
    if (!/^[\w.\-]{2,}@[a-z]{2,}$/i.test(value)) {
      return { ok: false, reason: "That does not look like a UPI ID." };
    }
    if (value.toLowerCase().startsWith("fail@")) {
      return { ok: false, reason: "The UPI request was declined." };
    }
    return { ok: true };
  }

  return { ok: true };
}

/* ── Step 2: confirm ──────────────────────────────────────────────────────── */

const ConfirmSchema = z.object({
  reference: z.string().trim().min(4).max(40),
  credential: z.string().trim().max(120).optional(),
});

/**
 * Complete an attempt.
 *
 * Note the ordering, which is the only genuinely delicate thing here. The row is
 * **claimed first** — a conditional update from `pending` to `succeeded` — and
 * only then is the money posted. Reserving before performing gives at-most-once:
 * two concurrent confirms race for one row and exactly one wins.
 *
 * The alternative, crediting first and marking after, is worse: a failure between
 * the two leaves a paid customer with a `pending` row that a retry would credit a
 * second time. If the ledger posting fails after a successful claim, the row is
 * walked back to `failed` so the customer can try again, and nothing was credited.
 *
 * The amount is read from the row, never from the form. The client supplies only
 * a reference and a fake credential.
 */
export async function confirmTopUp(
  _prev: TopUpState,
  formData: FormData,
): Promise<TopUpState> {
  const parsed = ConfirmSchema.safeParse({
    reference: formData.get("reference"),
    credential: formData.get("credential") ?? undefined,
  });

  if (!parsed.success) return FAILED("That payment could not be completed.");

  const user = await currentUser();
  if (!user) return FAILED("Sign in to add funds.");

  const admin = createAdminClient();

  const { data: attempt, error: readError } = await admin
    .from("wallet_topups")
    .select("id, reference, amount_minor, method, status, ledger_posted")
    .eq("reference", parsed.data.reference)
    .eq("user_id", user.id)
    .maybeSingle<{
      id: string;
      reference: string;
      amount_minor: number;
      method: TopUpMethod;
      status: string;
      ledger_posted: boolean;
    }>();

  if (readError || !attempt) {
    return FAILED("That payment could not be found. Start again.");
  }

  if (attempt.status !== "pending") {
    return {
      error: null,
      intent: null,
      outcome: {
        ok: attempt.status === "succeeded",
        reference: attempt.reference,
        amountMinor: attempt.amount_minor,
        message:
          attempt.status === "succeeded"
            ? `${formatMoney(attempt.amount_minor)} was already added.`
            : "That payment was declined. Start a new one to try again.",
      },
    };
  }

  /* The gateway decision comes before the claim: a decline should record a
     failure, not consume the pending row as if it had been paid. */
  const verdict = simulateGateway(attempt.method, parsed.data.credential ?? "");

  if (!verdict.ok) {
    await admin
      .from("wallet_topups")
      .update({
        status: "failed",
        failure_reason: verdict.reason,
        completed_at: new Date().toISOString(),
      })
      .eq("id", attempt.id)
      .eq("status", "pending");

    revalidatePath("/dashboard/wallet");

    return {
      error: null,
      intent: null,
      outcome: {
        ok: false,
        reference: attempt.reference,
        amountMinor: attempt.amount_minor,
        message: verdict.reason,
      },
    };
  }

  // Claim. `status` and `ledger_posted` both gate it, so this succeeds for
  // exactly one caller no matter how many arrive at once.
  const { data: claimed, error: claimError } = await admin
    .from("wallet_topups")
    .update({
      status: "succeeded",
      ledger_posted: true,
      completed_at: new Date().toISOString(),
    })
    .eq("id", attempt.id)
    .eq("status", "pending")
    .eq("ledger_posted", false)
    .select("id, amount_minor")
    .maybeSingle<{ id: string; amount_minor: number }>();

  if (claimError) {
    console.error("[topup] claim failed", { code: claimError.code, message: claimError.message });
    return FAILED("That payment could not be completed. Nothing has been charged.");
  }

  if (!claimed) {
    // Somebody else claimed it between the read and the update. Their credit is
    // the real one; this caller reports success without posting a second.
    return {
      error: null,
      intent: null,
      outcome: {
        ok: true,
        reference: attempt.reference,
        amountMinor: attempt.amount_minor,
        message: `${formatMoney(attempt.amount_minor)} added.`,
      },
    };
  }

  const credit = await creditFromPlatform({
    kind: "topup",
    amountMinor: claimed.amount_minor,
    to: { kind: "user", ownerId: user.id },
    memo: `Top-up ${attempt.reference} (${attempt.method})`,
  });

  if (!credit.ok) {
    /* Walk the claim back so the customer is not left holding a "succeeded" row
       with no money behind it. Nothing was credited, so a fresh attempt is safe. */
    await admin
      .from("wallet_topups")
      .update({
        status: "failed",
        ledger_posted: false,
        failure_reason: "Balance could not be credited",
        completed_at: new Date().toISOString(),
      })
      .eq("id", claimed.id);

    console.error("[topup] credit failed after claim — attempt reverted", {
      reference: attempt.reference,
      amountMinor: claimed.amount_minor,
    });

    return FAILED("Your balance could not be credited. Nothing has been charged.");
  }

  revalidatePath("/dashboard/wallet");
  revalidatePath("/dashboard/billing");
  revalidatePath("/dashboard");

  return {
    error: null,
    intent: null,
    outcome: {
      ok: true,
      reference: attempt.reference,
      amountMinor: claimed.amount_minor,
      message: `${formatMoney(claimed.amount_minor)} added to your balance.`,
    },
  };
}
