"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";

import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { formatMoney } from "@/lib/format";
import { creditFromPlatform } from "@/lib/wallet/server";
import { getRequestOrigin } from "@/lib/auth/origin";
import {
  buildPayUrl,
  isUnreachableFromPhone,
  payQrSvg,
} from "@/lib/wallet/upi";
import {
  TOPUP_MAX_MINOR,
  TOPUP_MIN_MINOR,
  type TopUpIntent,
  type TopUpMethod,
  type TopUpState,
} from "@/lib/wallet/topup-state";

/**
 * Customer-funded top-ups, through a simulated gateway.
 *
 * Two steps on purpose, mirroring how a real provider works: create an intent,
 * then confirm it. A single action that took an amount and credited a balance
 * would be the same code with no audit trail and nowhere to put a decline — and
 * it would have to be thrown away when a real gateway lands, rather than having
 * its confirm step swapped.
 *
 * **This lets an untrusted party initiate a credit,** which is the whole point
 * and also the risk. Four things carry that:
 *
 *   1. Every attempt is a row in `wallet_topups`, including the failures, so a
 *      credit always has an intent behind it.
 *   2. The confirm step *claims* the row with a conditional update before it
 *      posts any money. A double-submit or a refreshed page finds nothing left to
 *      claim and credits nothing — the same trick `resolveDispute` uses with
 *      `.neq("status", "resolved")`.
 *   3. Amounts are bounded in this file and again by a check constraint.
 *   4. The customer never supplies the amount at confirm time. It is read back
 *      from the row, so tampering with the confirm payload cannot change what
 *      gets credited.
 *
 * When a real provider replaces this, `simulateGateway` is the only function
 * that goes; the intent row, the claim, and the ledger posting all stay.
 */

/* ── Shared ───────────────────────────────────────────────────────────────── */

const FAILED = (error: string): TopUpState => ({ error, intent: null, outcome: null });

const METHODS = ["card", "upi", "netbanking"] as const satisfies readonly TopUpMethod[];

/**
 * "500" / "500.50" → paise. Rejects a third decimal rather than rounding it,
 * matching `rupeesToPaise` in the booking actions.
 */
function rupeesToPaise(input: string): number | null {
  const trimmed = input.trim().replace(/^₹/, "").replace(/,/g, "");
  if (!/^\d+(\.\d{1,2})?$/.test(trimmed)) return null;
  return Math.round(Number(trimmed) * 100);
}

async function currentUser() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return user;
}

/* ── Step 1: the intent ───────────────────────────────────────────────────── */

const IntentSchema = z.object({
  amount: z.string().trim().min(1, "Enter an amount."),
  method: z.enum(METHODS),
  // Generated by the client, one per attempt. Not trusted for anything except
  // de-duplication, and the unique index is what actually enforces that.
  idempotencyKey: z.string().trim().min(8).max(100),
});

export async function createTopUpIntent(
  _prev: TopUpState,
  formData: FormData,
): Promise<TopUpState> {
  const parsed = IntentSchema.safeParse({
    amount: formData.get("amount"),
    method: formData.get("method"),
    idempotencyKey: formData.get("idempotencyKey"),
  });

  if (!parsed.success) {
    return FAILED(parsed.error.issues[0]?.message ?? "Check the amount and try again.");
  }

  const user = await currentUser();
  if (!user) return FAILED("Sign in to add funds.");

  const minor = rupeesToPaise(parsed.data.amount);
  if (minor === null) {
    return FAILED("Enter the amount in rupees, like 500 or 500.50.");
  }
  if (minor < TOPUP_MIN_MINOR) {
    return FAILED(`The smallest top-up is ${formatMoney(TOPUP_MIN_MINOR)}.`);
  }
  if (minor > TOPUP_MAX_MINOR) {
    return FAILED(`The largest single top-up is ${formatMoney(TOPUP_MAX_MINOR)}.`);
  }

  const admin = createAdminClient();

  const { data, error } = await admin
    .from("wallet_topups")
    .insert({
      user_id: user.id,
      amount_minor: minor,
      method: parsed.data.method,
      idempotency_key: parsed.data.idempotencyKey,
    })
    .select("reference, amount_minor, method, pay_token")
    .maybeSingle<{
      reference: string;
      amount_minor: number;
      method: TopUpMethod;
      pay_token: string;
    }>();

  if (error) {
    // A repeated key means the customer already started this exact attempt —
    // most likely a double-click. Recover by handing back the existing intent
    // rather than refusing, so they land on the gateway either way.
    if (error.code === "23505") {
      const { data: existing } = await admin
        .from("wallet_topups")
        .select("reference, amount_minor, method, status, pay_token")
        .eq("user_id", user.id)
        .eq("idempotency_key", parsed.data.idempotencyKey)
        .maybeSingle<{
          reference: string;
          amount_minor: number;
          method: TopUpMethod;
          status: string;
          pay_token: string;
        }>();

      if (existing && existing.status === "pending") {
        return {
          error: null,
          intent: await withScanTarget({
            reference: existing.reference,
            amountMinor: existing.amount_minor,
            method: existing.method,
          }, existing.pay_token),
          outcome: null,
        };
      }

      return FAILED("That payment has already been processed. Refresh to see your balance.");
    }

    console.error("[topup] intent creation failed", {
      code: error.code,
      message: error.message,
    });

    if (error.code === "42P01" || error.code === "PGRST205") {
      return FAILED("Top-ups are not set up on this database yet.");
    }
    return FAILED("That payment could not be started. Try again in a moment.");
  }

  if (!data) return FAILED("That payment could not be started. Try again in a moment.");

  return {
    error: null,
    intent: await withScanTarget({
      reference: data.reference,
      amountMinor: data.amount_minor,
      method: data.method,
    }, data.pay_token),
    outcome: null,
  };
}

/**
 * Attach the scannable QR, for UPI only.
 *
 * Split out so both return paths above — the fresh intent and the recovered
 * duplicate — produce the same shape. A QR on one and not the other would mean a
 * double-click silently lost the ability to scan.
 *
 * The origin comes from the request, so the QR encodes whatever host the operator
 * is actually browsing. When that is loopback the flag is set rather than the QR
 * suppressed: the code still scans, it just cannot be reached from a phone, and
 * the UI explains that instead of showing nothing.
 */
async function withScanTarget(
  intent: TopUpIntent,
  payToken: string,
): Promise<TopUpIntent> {
  if (intent.method !== "upi") return intent;

  const origin = await getRequestOrigin();
  const payUrl = buildPayUrl(origin, payToken);

  return {
    ...intent,
    qrSvg: await payQrSvg(payUrl),
    payUrl,
    payUrlUnreachable: isUnreachableFromPhone(origin),
  };
}

/* ── The simulated gateway ────────────────────────────────────────────────── */

/**
 * Stands in for a payment provider. Deterministic, so the decline path is
 * testable without waiting for a real bank to refuse something.
 *
 *   • card       — declines when the number ends in `0000`
 *   • upi        — declines when the id begins `fail@`
 *   • netbanking — always succeeds; there is no credential to get wrong
 *
 * These rules are shown in the UI. That is deliberate: it is a mock, and hiding
 * how to trigger a failure would make the failure path untestable by anyone but
 * whoever wrote it.
 */
function simulateGateway(
  method: TopUpMethod,
  credential: string,
): { ok: true } | { ok: false; reason: string } {
  const value = credential.trim();

  if (method === "card") {
    const digits = value.replace(/\s+/g, "");
    if (!/^\d{16}$/.test(digits)) {
      return { ok: false, reason: "That card number is not 16 digits." };
    }
    if (digits.endsWith("0000")) {
      return { ok: false, reason: "Your bank declined that card." };
    }
    return { ok: true };
  }

  if (method === "upi") {
    if (!/^[\w.\-]{2,}@[a-z]{2,}$/i.test(value)) {
      return { ok: false, reason: "That does not look like a UPI ID." };
    }
    if (value.toLowerCase().startsWith("fail@")) {
      return { ok: false, reason: "The UPI request was declined." };
    }
    return { ok: true };
  }

  return { ok: true };
}

/* ── Step 2: confirm ──────────────────────────────────────────────────────── */

const ConfirmSchema = z.object({
  reference: z.string().trim().min(4).max(40),
  credential: z.string().trim().max(120).optional(),
});

/** The columns settling an attempt needs. Both entry points select exactly these. */
interface PendingAttempt {
  id: string;
  user_id: string;
  reference: string;
  amount_minor: number;
  method: TopUpMethod;
  status: string;
  ledger_posted: boolean;
}

const ATTEMPT_COLUMNS =
  "id, user_id, reference, amount_minor, method, status, ledger_posted";

/**
 * Settle one attempt: decide, claim, credit.
 *
 * Shared by both entry points — the desktop form, which authorises by session,
 * and the scanned QR, which authorises by capability token. They differ only in
 * how they *find* the attempt; what happens to it afterwards must be identical,
 * so it lives here once. Two implementations of a claim would be two chances to
 * get at-most-once wrong.
 *
 * The ordering is the delicate part. The row is **claimed first** — a conditional
 * update from `pending` to `succeeded` — and only then is money posted. Reserving
 * before performing gives at-most-once: two concurrent confirms race for one row
 * and exactly one wins. That is not hypothetical here, because the desktop form
 * and the phone can both be looking at the same attempt.
 *
 * Crediting first and marking after would be worse: a failure between the two
 * leaves a paid customer with a `pending` row that a retry would credit again. If
 * the ledger posting fails after a successful claim the row is walked back, so
 * nothing was credited and a fresh attempt is safe.
 *
 * The amount always comes from the row, never from the request.
 */
async function settleAttempt(
  attempt: PendingAttempt,
  credential: string,
): Promise<TopUpState> {
  const admin = createAdminClient();

  if (attempt.status !== "pending") {
    return {
      error: null,
      intent: null,
      outcome: {
        ok: attempt.status === "succeeded",
        reference: attempt.reference,
        amountMinor: attempt.amount_minor,
        message:
          attempt.status === "succeeded"
            ? `${formatMoney(attempt.amount_minor)} was already added.`
            : "That payment was declined. Start a new one to try again.",
      },
    };
  }

  /* The gateway decision comes before the claim: a decline should record a
     failure, not consume the pending row as if it had been paid. */
  const verdict = simulateGateway(attempt.method, credential);

  if (!verdict.ok) {
    await admin
      .from("wallet_topups")
      .update({
        status: "failed",
        failure_reason: verdict.reason,
        completed_at: new Date().toISOString(),
      })
      .eq("id", attempt.id)
      .eq("status", "pending");

    revalidatePath("/dashboard/wallet");

    return {
      error: null,
      intent: null,
      outcome: {
        ok: false,
        reference: attempt.reference,
        amountMinor: attempt.amount_minor,
        message: verdict.reason,
      },
    };
  }

  const { data: claimed, error: claimError } = await admin
    .from("wallet_topups")
    .update({
      status: "succeeded",
      ledger_posted: true,
      completed_at: new Date().toISOString(),
    })
    .eq("id", attempt.id)
    .eq("status", "pending")
    .eq("ledger_posted", false)
    .select("id, amount_minor")
    .maybeSingle<{ id: string; amount_minor: number }>();

  if (claimError) {
    console.error("[topup] claim failed", {
      code: claimError.code,
      message: claimError.message,
    });
    return FAILED("That payment could not be completed. Nothing has been charged.");
  }

  if (!claimed) {
    // Somebody else claimed it between the read and the update — the desktop and
    // the phone both confirming is the likely case. Their credit is the real one;
    // this caller reports success without posting a second.
    return {
      error: null,
      intent: null,
      outcome: {
        ok: true,
        reference: attempt.reference,
        amountMinor: attempt.amount_minor,
        message: `${formatMoney(attempt.amount_minor)} added.`,
      },
    };
  }

  const credit = await creditFromPlatform({
    kind: "topup",
    amountMinor: claimed.amount_minor,
    to: { kind: "user", ownerId: attempt.user_id },
    memo: `Top-up ${attempt.reference} (${attempt.method})`,
  });

  if (!credit.ok) {
    /* Walk the claim back so nobody holds a "succeeded" row with no money behind
       it. Nothing was credited, so a fresh attempt is safe. */
    await admin
      .from("wallet_topups")
      .update({
        status: "failed",
        ledger_posted: false,
        failure_reason: "Balance could not be credited",
        completed_at: new Date().toISOString(),
      })
      .eq("id", claimed.id);

    console.error("[topup] credit failed after claim — attempt reverted", {
      reference: attempt.reference,
      amountMinor: claimed.amount_minor,
    });

    return FAILED("Your balance could not be credited. Nothing has been charged.");
  }

  revalidatePath("/dashboard/wallet");
  revalidatePath("/dashboard/billing");
  revalidatePath("/dashboard");

  return {
    error: null,
    intent: null,
    outcome: {
      ok: true,
      reference: attempt.reference,
      amountMinor: claimed.amount_minor,
      message: `${formatMoney(claimed.amount_minor)} added to your balance.`,
    },
  };
}

/**
 * Complete an attempt from the dashboard, authorised by the session.
 *
 * Scoped to the caller's own rows by `user_id`, so a reference belonging to
 * somebody else resolves to nothing.
 */
export async function confirmTopUp(
  _prev: TopUpState,
  formData: FormData,
): Promise<TopUpState> {
  const parsed = ConfirmSchema.safeParse({
    reference: formData.get("reference"),
    credential: formData.get("credential") ?? undefined,
  });

  if (!parsed.success) return FAILED("That payment could not be completed.");

  const user = await currentUser();
  if (!user) return FAILED("Sign in to add funds.");

  const { data: attempt, error } = await createAdminClient()
    .from("wallet_topups")
    .select(ATTEMPT_COLUMNS)
    .eq("reference", parsed.data.reference)
    .eq("user_id", user.id)
    .maybeSingle<PendingAttempt>();

  if (error || !attempt) {
    return FAILED("That payment could not be found. Start again.");
  }

  return settleAttempt(attempt, parsed.data.credential ?? "");
}

const TokenConfirmSchema = z.object({
  // 32 bytes base64url. Length-bounded so a padded or truncated value is refused
  // before it ever reaches a query.
  token: z.string().trim().min(32).max(64),
  credential: z.string().trim().max(120).optional(),
});

/**
 * Complete an attempt from a scanned QR, authorised by the capability token alone.
 *
 * **There is no session here and there cannot be.** The phone that scanned the
 * code has never signed in to this app, so the token in the URL is the entire
 * authorisation — which is why it is 32 random bytes rather than the short
 * human-readable reference, and why it is never displayed anywhere.
 *
 * The token identifies the attempt and the attempt names its own user, so the
 * credit lands in the right wallet without the caller claiming an identity. A
 * token whose attempt is no longer `pending` settles to a report rather than a
 * second credit, so a re-scanned QR is harmless.
 */
export async function confirmTopUpByToken(
  _prev: TopUpState,
  formData: FormData,
): Promise<TopUpState> {
  const parsed = TokenConfirmSchema.safeParse({
    token: formData.get("token"),
    credential: formData.get("credential") ?? undefined,
  });

  if (!parsed.success) return FAILED("That payment link is not valid.");

  const { data: attempt, error } = await createAdminClient()
    .from("wallet_topups")
    .select(ATTEMPT_COLUMNS)
    .eq("pay_token", parsed.data.token)
    .maybeSingle<PendingAttempt>();

  if (error || !attempt) {
    // Deliberately the same message as a spent one: distinguishing "no such
    // token" from "token exists but is used" would make this an oracle.
    return FAILED("That payment link is not valid or has already been used.");
  }

  return settleAttempt(attempt, parsed.data.credential ?? "");
}

