import { CalendarPlus, Download } from "lucide-react";

import { Button } from "@/components/ui/button";

/**
 * Put a confirmed slot in the customer's own calendar.
 *
 * A server component, and deliberately two links rather than a picker: a
 * download and a URL both work without JavaScript, where a "choose your
 * calendar" menu is a client bundle for a decision most people make once.
 *
 * The `.ics` is generated by the route beside the booking page rather than
 * built here as a data URL. That route re-reads the booking and re-checks the
 * caller, so a copied link cannot hand someone else's appointment out — a data
 * URL assembled in this component would have to trust whatever it was passed.
 */

/** `2026-08-10T09:00:00.000Z` → `20260810T090000Z`, the form both formats use. */
function compactUtc(date: Date): string {
  return `${date.toISOString().replace(/[-:]/g, "").split(".")[0]}Z`;
}

export function AddToCalendar({
  reference,
  summary,
  start,
  end,
  location,
  description,
}: {
  reference: string;
  summary: string;
  start: Date;
  end: Date;
  location?: string | null;
  description?: string | null;
}) {
  const google = new URL("https://calendar.google.com/calendar/render");
  google.searchParams.set("action", "TEMPLATE");
  google.searchParams.set("text", summary);
  google.searchParams.set("dates", `${compactUtc(start)}/${compactUtc(end)}`);
  if (location) google.searchParams.set("location", location);
  if (description) google.searchParams.set("details", description);

  return (
    <div className="flex flex-col gap-2">
      <Button asChild variant="outline" size="sm" className="w-full">
        {/* `download` names the file for browsers that would otherwise save it
            as the route segment, "calendar", with no extension. */}
        <a href={`/dashboard/bookings/${encodeURIComponent(reference)}/calendar`} download={`${reference}.ics`}>
          <Download aria-hidden />
          Download .ics
        </a>
      </Button>

      <Button asChild variant="outline" size="sm" className="w-full">
        <a href={google.toString()} target="_blank" rel="noreferrer noopener">
          <CalendarPlus aria-hidden />
          Add to Google Calendar
        </a>
      </Button>
    </div>
  );
}
