"use client";

import * as React from "react";
import { CalendarX } from "lucide-react";

import { EmptyState } from "@/components/dashboard/empty-state";
import type { Slot, SlotDay } from "@/lib/bookings/slots";
import { formatTime } from "@/lib/format";
import { cn } from "@/lib/utils";

/**
 * Day tabs over a grid of times.
 *
 * Presentational on purpose. The slots are generated by the form above it, which
 * owns the chosen service and therefore the duration every slot is cut to.
 * Taking `SlotDay[]` rather than the generation inputs keeps that arithmetic in
 * one place and lets the form decide — during render — whether a slot picked
 * against an older duration still exists.
 *
 * Unavailable slots render `disabled`, never dropped. A grid that silently omits
 * 14:00 reads as "this shop stops at lunch"; a struck-through 14:00 reads as
 * "that one is taken", which is both true and what makes the next one credible.
 *
 * Times are formatted in the SHOP's timezone. Someone in Sydney booking a London
 * shop is agreeing to the shop's 09:30, and showing them their own 18:30 would
 * have them turn up on the wrong day.
 */

const TAB = "slot-day";

export function SlotPicker({
  days,
  timezone,
  selectedStart,
  onSelect,
  disabled = false,
}: {
  days: SlotDay[];
  timezone: string;
  /** ISO start of the chosen slot, or null. Owned by the form, not by this. */
  selectedStart: string | null;
  onSelect: (slot: Slot) => void;
  disabled?: boolean;
}) {
  const [pickedDay, setPickedDay] = React.useState<string | null>(null);

  // Derived, never synced. Changing service changes the duration, which
  // regenerates every day key: an effect reconciling `pickedDay` would paint the
  // stale day first, and `react-hooks/set-state-in-effect` is an error here.
  // Opening on the first day that has something bookable beats opening on a day
  // that is already fully booked.
  const fallback =
    days.find((day) => day.slots.some((slot) => slot.available)) ?? days[0] ?? null;
  const active = days.find((day) => day.day === pickedDay) ?? fallback;

  if (!active) {
    return (
      <EmptyState
        icon={CalendarX}
        title="No times to show"
        description="This shop has not published a bookable calendar yet. Send them a message and they will arrange a time with you."
      />
    );
  }

  const moveTab = (event: React.KeyboardEvent<HTMLDivElement>) => {
    const index = days.findIndex((day) => day.day === active.day);
    const step = event.key === "ArrowRight" ? 1 : event.key === "ArrowLeft" ? -1 : 0;

    let next = -1;
    if (step !== 0) next = (index + step + days.length) % days.length;
    else if (event.key === "Home") next = 0;
    else if (event.key === "End") next = days.length - 1;
    if (next < 0) return;

    const target = days[next];
    if (!target) return;

    event.preventDefault();
    setPickedDay(target.day);
    // Every tab stays mounted — only the panel swaps — so focus can move now
    // rather than waiting on a re-render.
    document.getElementById(`${TAB}-${target.day}`)?.focus();
  };

  return (
    <div>
      <div
        role="tablist"
        aria-label="Days with times available"
        onKeyDown={moveTab}
        className="-mx-1 flex gap-1 overflow-x-auto border-b border-hairline px-1 pb-2"
      >
        {days.map((day) => {
          const isActive = day.day === active.day;
          const open = day.slots.filter((slot) => slot.available).length;

          return (
            <button
              key={day.day}
              id={`${TAB}-${day.day}`}
              type="button"
              role="tab"
              aria-selected={isActive}
              aria-controls={`${TAB}-panel-${day.day}`}
              tabIndex={isActive ? 0 : -1}
              onClick={() => setPickedDay(day.day)}
              className={cn(
                "shrink-0 rounded-machined border px-3 py-2 text-center transition-colors",
                "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-signal",
                isActive
                  ? "border-enamel bg-enamel text-bench"
                  : "border-hairline bg-chalk text-steel hover:border-steel-soft hover:text-enamel",
              )}
            >
              <span className="block whitespace-nowrap font-display text-sm uppercase tracking-wide">
                {day.label}
              </span>
              <span
                className={cn(
                  "block pt-0.5 font-mono text-eyebrow tabular-nums",
                  isActive ? "text-bench" : open > 0 ? "text-signal" : "text-steel-soft",
                )}
              >
                {open > 0 ? `${open} free` : "Full"}
              </span>
            </button>
          );
        })}
      </div>

      <div
        role="tabpanel"
        id={`${TAB}-panel-${active.day}`}
        aria-labelledby={`${TAB}-${active.day}`}
        className="pt-3"
      >
        <fieldset disabled={disabled}>
          <legend className="sr-only">Times on {active.label}</legend>

          <div className="grid grid-cols-3 gap-2 sm:grid-cols-4 lg:grid-cols-5">
            {active.slots.map((slot) => {
              const startIso = slot.start.toISOString();

              return (
                <label key={startIso} className="block">
                  {/* Named `slotChoice`, not `slotStart`: only the open day's
                      radios are mounted, so a slot chosen on Tuesday would stop
                      posting the moment Wednesday is opened. The form carries the
                      real `slotStart`/`slotEnd` in hidden fields instead. */}
                  <input
                    type="radio"
                    name="slotChoice"
                    value={startIso}
                    checked={startIso === selectedStart}
                    disabled={disabled || !slot.available}
                    onChange={() => onSelect(slot)}
                    className="peer sr-only"
                  />
                  <span
                    className={cn(
                      "block rounded-machined border py-2 text-center font-mono text-sm tabular-nums transition-colors",
                      slot.available
                        ? "cursor-pointer border-hairline bg-chalk text-enamel hover:border-signal hover:text-signal"
                        : "cursor-not-allowed border-hairline bg-bench-sunk text-steel-soft line-through",
                      "peer-checked:border-signal peer-checked:bg-signal peer-checked:text-white",
                      "peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-signal",
                      "peer-disabled:cursor-not-allowed",
                    )}
                  >
                    {formatTime(slot.start, timezone)}
                    {slot.available ? null : <span className="sr-only"> — taken</span>}
                  </span>
                </label>
              );
            })}
          </div>
        </fieldset>
      </div>
    </div>
  );
}
