"use client";

import * as React from "react";
import { useActionState } from "react";
import { useTranslations } from "next-intl";
import { AlertTriangle, CheckCircle2, CreditCard, Landmark, Smartphone } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { formatMoney } from "@/lib/format";
import { confirmTopUp, createTopUpIntent } from "@/lib/wallet/topup";
import {
  TOPUP_INITIAL_STATE,
  TOPUP_MAX_MINOR,
  TOPUP_MIN_MINOR,
  TOPUP_PRESETS,
  type TopUpMethod,
} from "@/lib/wallet/topup-state";
import { cn } from "@/lib/utils";

/**
 * The add-funds portal.
 *
 * Two steps, because the server has two: choose an amount and a method, which
 * creates an intent, then present a credential against that intent. Which step
 * renders is decided by what the server returned — `state.intent` — rather than
 * by a local flag, so the UI cannot show a gateway for an intent that was never
 * created.
 *
 * The gateway is simulated and the banner says so. The test values that force a
 * decline are printed on the form on purpose: it is a mock, and a failure path
 * nobody can reach is a failure path nobody has tested.
 *
 * The idempotency key is minted once per attempt and held in state, so a
 * double-click posts the same key twice and the second is de-duplicated by the
 * unique index rather than creating a second intent.
 */

/** Payment methods, in display order, mapped to their catalogue label keys. */
const METHOD_ORDER: readonly TopUpMethod[] = ["card", "upi", "netbanking"];

const METHOD_MSG: Record<TopUpMethod, string> = {
  card: "methodCard",
  upi: "methodUpi",
  netbanking: "methodNetbanking",
};

const METHOD_ICONS: Record<TopUpMethod, typeof CreditCard> = {
  card: CreditCard,
  upi: Smartphone,
  netbanking: Landmark,
};

/**
 * Which methods present a credential field, and which of the catalogue's
 * `card*`/`upi*` keys drive its label, placeholder and hint. Net banking has no
 * field — the gateway is simulated end to end.
 */
function credentialField(
  t: (key: string) => string,
  method: TopUpMethod,
): { label: string; placeholder: string; hint: string } | null {
  if (method === "netbanking") return null;
  const prefix = method === "card" ? "card" : "upi";
  return {
    label: t(`${prefix}Label`),
    placeholder: t(`${prefix}Placeholder`),
    hint: t(`${prefix}Hint`),
  };
}

function randomKey(): string {
  // `crypto.randomUUID` is available in every browser this app supports, and the
  // fallback keeps it from throwing in a non-secure context during local work.
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return `k-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

export function WalletTopUp({ balanceMinor }: { balanceMinor: number }) {
  const [intentState, startIntent, starting] = useActionState(
    createTopUpIntent,
    TOPUP_INITIAL_STATE,
  );
  const [confirmState, confirm, confirming] = useActionState(
    confirmTopUp,
    TOPUP_INITIAL_STATE,
  );

  const [method, setMethod] = React.useState<TopUpMethod>("card");
  const [amount, setAmount] = React.useState("");

  /*
   * One key per attempt.
   *
   * Regenerated by the "Add more" / "Try again" button below rather than by an
   * effect watching the outcome. Syncing state from an effect is a lint error
   * here and it is a lint error for a reason (see the header of
   * `booking-form.tsx`) — and it is also the wrong model: a new key belongs to a
   * new attempt, and a new attempt starts when the person says so, not when a
   * render happens to notice the last one finished.
   */
  const [key, setKey] = React.useState(randomKey);

  const t = useTranslations("wallet");

  const outcome = confirmState.outcome;
  const intent = outcome ? null : intentState.intent;
  const error = confirmState.error ?? intentState.error;

  function startAnother() {
    setAmount("");
    setKey(randomKey());
  }

  if (outcome) {
    return (
      <div className="flex flex-col gap-3">
        <p
          role="status"
          className={cn(
            "flex items-start gap-2 rounded-machined border px-3 py-2.5 text-sm leading-relaxed",
            outcome.ok
              ? "border-verdigris/30 bg-verdigris-wash text-enamel"
              : "border-rust/30 bg-rust-wash text-rust",
          )}
        >
          {outcome.ok ? (
            <CheckCircle2 aria-hidden className="mt-0.5 size-4 shrink-0 text-verdigris" />
          ) : (
            <AlertTriangle aria-hidden className="mt-0.5 size-4 shrink-0" />
          )}
          <span>
            {outcome.message}
            <span className="block pt-0.5 font-mono text-eyebrow uppercase tracking-[0.14em] text-steel-soft">
              {outcome.reference}
            </span>
          </span>
        </p>

        <div>
          <Button type="button" size="sm" variant="outline" onClick={startAnother}>
            {outcome.ok ? t("topup.addMore") : t("topup.tryAgain")}
          </Button>
        </div>
      </div>
    );
  }

  /* ── Step 2 ─────────────────────────────────────────────────────────────── */

  if (intent) {
    const field = credentialField(t, intent.method);

    return (
      <form key="gateway" action={confirm} className="flex flex-col gap-4">
        <input type="hidden" name="reference" value={intent.reference} />

        <div className="rounded-machined border border-hairline bg-bench p-3">
          <p className="flex items-baseline justify-between gap-3 text-sm">
            <span className="text-steel">{t("topup.paying")}</span>
            <span className="font-mono text-lg tabular-nums text-enamel">
              {formatMoney(intent.amountMinor)}
            </span>
          </p>
          <p className="flex items-baseline justify-between gap-3 pt-1 text-sm">
            <span className="text-steel">{t("topup.method")}</span>
            <span className="text-enamel">{t(METHOD_MSG[intent.method])}</span>
          </p>
          <p className="pt-2 font-mono text-eyebrow uppercase tracking-[0.14em] text-steel-soft">
            {intent.reference}
          </p>
        </div>

        {intent.qrSvg ? (
          <div className="flex flex-col items-center gap-3 rounded-machined border border-hairline bg-chalk p-4">
            <p className="eyebrow">{t("topup.scanToPay")}</p>

            {/*
              The SVG is generated by `qrcode` on the server from a URL we built,
              so there is no user input in it — but it is still injected markup, so
              it is worth saying why that is safe rather than leaving a reader to
              wonder. Rendered inline rather than as an <img> so it stays crisp and
              costs no extra request.
            */}
            <div
              className="w-[200px] [&>svg]:h-auto [&>svg]:w-full"
              dangerouslySetInnerHTML={{ __html: intent.qrSvg }}
            />

            {intent.payUrlUnreachable ? (
              <p className="flex items-start gap-2 text-xs leading-relaxed text-rust">
                <AlertTriangle aria-hidden className="mt-0.5 size-3.5 shrink-0" />
                <span>
                  {t.rich("topup.qrLocalhost", {
                    mono: (chunks) => <span className="font-mono">{chunks}</span>,
                  })}
                </span>
              </p>
            ) : (
              <p className="text-center text-xs leading-relaxed text-steel">
                {t("topup.qrHelp")}
              </p>
            )}

            {intent.payUrl ? (
              <p className="w-full break-all text-center font-mono text-eyebrow text-steel-soft">
                {intent.payUrl}
              </p>
            ) : null}
          </div>
        ) : null}

        {field ? (
          <div className="flex flex-col gap-1.5">
            <label htmlFor="topup-credential" className="eyebrow">
              {field.label}
            </label>
            <Input
              id="topup-credential"
              name="credential"
              required
              autoComplete="off"
              inputMode={intent.method === "card" ? "numeric" : "text"}
              placeholder={field.placeholder}
              className="font-mono tabular-nums"
            />
            <p className="text-xs leading-relaxed text-steel">{field.hint}</p>
          </div>
        ) : (
          <p className="text-sm leading-relaxed text-steel">
            {t("topup.netbankingNote")}
          </p>
        )}

        {error ? (
          <p role="alert" className="text-sm text-rust">
            {error}
          </p>
        ) : null}

        <div>
          <Button type="submit" size="sm" disabled={confirming}>
            {confirming
              ? t("topup.processing")
              : t("topup.pay", { amount: formatMoney(intent.amountMinor) })}
          </Button>
        </div>
      </form>
    );
  }

  /* ── Step 1 ─────────────────────────────────────────────────────────────── */

  return (
    <form key="amount" action={startIntent} className="flex flex-col gap-4">
      <input type="hidden" name="idempotencyKey" value={key} />
      <input type="hidden" name="method" value={method} />

      <div className="flex flex-col gap-1.5">
        <span className="eyebrow">{t("topup.amount")}</span>
        <div className="flex flex-wrap gap-2">
          {TOPUP_PRESETS.map((preset) => (
            <Button
              key={preset}
              type="button"
              size="sm"
              variant={amount === String(preset / 100) ? "primary" : "outline"}
              onClick={() => setAmount(String(preset / 100))}
            >
              {formatMoney(preset)}
            </Button>
          ))}
        </div>
      </div>

      <div className="flex flex-col gap-1.5">
        <label htmlFor="topup-amount" className="eyebrow">
          {t("topup.orTypeAmount")}
        </label>
        <Input
          id="topup-amount"
          name="amount"
          required
          inputMode="decimal"
          autoComplete="off"
          value={amount}
          onChange={(event) => setAmount(event.target.value)}
          placeholder={t("topup.amountPlaceholder")}
          // Mirrors the server's own test so a stray third decimal is caught
          // before a round-trip rather than after one.
          pattern="₹?\d+(\.\d{1,2})?"
          title={t("topup.amountTitle")}
          className="font-mono tabular-nums"
        />
        <p className="text-xs leading-relaxed text-steel">
          {t("topup.amountRange", {
            min: formatMoney(TOPUP_MIN_MINOR),
            max: formatMoney(TOPUP_MAX_MINOR),
            balance: formatMoney(balanceMinor),
          })}
        </p>
      </div>

      <div className="flex flex-col gap-1.5">
        <span className="eyebrow">{t("topup.payWith")}</span>
        <div className="grid gap-2 sm:grid-cols-3">
          {METHOD_ORDER.map((value) => {
            const Icon = METHOD_ICONS[value];
            const active = method === value;

            return (
              <button
                key={value}
                type="button"
                onClick={() => setMethod(value)}
                aria-pressed={active}
                className={cn(
                  "flex items-center gap-2 rounded-machined border px-3 py-2.5 text-sm transition-colors",
                  active
                    ? "border-signal bg-signal-wash text-enamel"
                    : "border-hairline bg-bench text-steel hover:border-steel-soft",
                )}
              >
                <Icon aria-hidden className="size-4 shrink-0" />
                {t(METHOD_MSG[value])}
              </button>
            );
          })}
        </div>
      </div>

      {error ? (
        <p role="alert" className="text-sm text-rust">
          {error}
        </p>
      ) : null}

      <div>
        <Button type="submit" size="sm" disabled={starting}>
          {starting ? t("topup.starting") : t("topup.continue")}
        </Button>
      </div>
    </form>
  );
}
