-- ════════════════════════════════════════════════════════════════════════════
-- 003 — Shop suspension and admin notices
--
-- Two moderation tools that the platform had no way to express:
--
--   1. **Suspension.** Distinct from `is_hidden`, which means "submitted, not
--      reviewed yet". A suspension is a decision taken *against* a shop that was
--      already trading, so it carries a reason the owner is shown verbatim and
--      it has to survive independently — lifting a suspension must not silently
--      publish a shop that was also still awaiting its first review.
--
--   2. **Notices.** A message from the platform to one shop owner, which they
--      have to acknowledge. Deliberately not `notifications`: those are
--      generated by product events and read casually. A notice is written by a
--      person, and the point is knowing it was seen.
--
-- Idempotent throughout; safe to re-run.
-- ════════════════════════════════════════════════════════════════════════════

-- ─── Suspension columns ─────────────────────────────────────────────────────

alter table fixer_profiles
  add column if not exists suspended_at     timestamptz,
  add column if not exists suspended_reason text,
  add column if not exists suspended_by     uuid;

comment on column fixer_profiles.suspended_at is
  'Set when an admin suspends the shop. Non-null means suspended: hidden from the directory, cannot accept bookings, and the owner is shown the reason on their dashboard.';

comment on column fixer_profiles.suspended_by is
  'seo_admins.id. No FK — that table belongs to the admin app, and removing an admin must not erase the record of what they did.';

-- Partial: the suspended set is tiny and is the only one ever filtered on.
create index if not exists fixer_profiles_suspended_idx
  on fixer_profiles (suspended_at)
  where suspended_at is not null;

-- ─── Notices ────────────────────────────────────────────────────────────────

create table if not exists shop_notices (
  id              uuid primary key default gen_random_uuid(),
  fixer_id        uuid not null references fixer_profiles (id) on delete cascade,
  sent_by         uuid,
  subject         text not null,
  body            text not null,
  severity        text not null default 'info',
  acknowledged_at timestamptz,
  created_at      timestamptz not null default now(),

  constraint shop_notices_severity_valid
    check (severity in ('info', 'warning', 'urgent')),
  constraint shop_notices_subject_len check (length(btrim(subject)) between 2 and 200),
  constraint shop_notices_body_len    check (length(btrim(body))    between 2 and 4000)
);

comment on table shop_notices is
  'Platform-to-shop messages requiring acknowledgement. Written only by the admin app via the service-role client; owners may read and acknowledge their own.';

create index if not exists shop_notices_shop_idx
  on shop_notices (fixer_id, created_at desc);

-- What the dashboard queries on every load, so it gets its own partial index.
create index if not exists shop_notices_unread_idx
  on shop_notices (fixer_id)
  where acknowledged_at is null;

alter table shop_notices enable row level security;

-- No INSERT policy on purpose: notices come from the admin app's service-role
-- client, which bypasses RLS. Without one, an owner cannot write themselves a
-- notice — and there is no legitimate case where they should.
drop policy if exists "owner reads own notices" on shop_notices;
create policy "owner reads own notices"
  on shop_notices for select
  to authenticated
  using (owns_shop(fixer_id));

drop policy if exists "owner acknowledges own notices" on shop_notices;
create policy "owner acknowledges own notices"
  on shop_notices for update
  to authenticated
  using (owns_shop(fixer_id))
  with check (owns_shop(fixer_id));

-- ─── Suspension takes effect everywhere ─────────────────────────────────────
--
-- A suspension that leaves the shop in search is not a suspension. Both the read
-- policy and the directory function have to honour it, exactly as they honour
-- `is_hidden` — one enforcing it and the other not is how a suspended business
-- keeps taking bookings.
--
-- The owner still reads their own row either way. That is what lets their
-- dashboard show the suspension notice rather than an empty screen.

drop policy if exists "Public fixer profiles"          on fixer_profiles;
drop policy if exists "profiles readable by all"        on fixer_profiles;
drop policy if exists "visible shops readable by all"   on fixer_profiles;

create policy "visible shops readable by all"
  on fixer_profiles for select
  using (
    (is_hidden = false and suspended_at is null)
    or owner_id = (select auth.uid())
  );

create or replace function search_fixers(
  min_lat              double precision default -90,
  max_lat              double precision default 90,
  min_lng              double precision default -180,
  max_lng              double precision default 180,
  category_slug        text default null,
  search_query         text default null,
  min_rating           numeric default 0,
  require_home_service boolean default false,
  require_pickup_drop  boolean default false,
  require_in_shop      boolean default false,
  result_limit         integer default 100
)
returns setof fixer_profiles
language sql
stable
as $$
  select f.*
    from fixer_profiles f
   where f.is_hidden = false
     and f.suspended_at is null
     and (
       (f.lat between min_lat and max_lat and f.lng between min_lng and max_lng)
       or (
         -- A shop with no coordinates can't be placed on the map, so it only
         -- surfaces when the caller hasn't narrowed to a viewport.
         f.lat is null
         and min_lat <= -90 and max_lat >= 90
         and min_lng <= -180 and max_lng >= 180
       )
     )
     and f.rating_avg >= min_rating
     and (not require_home_service or f.offers_home_service)
     and (not require_pickup_drop  or f.offers_pickup_drop)
     and (not require_in_shop      or f.offers_in_shop)
     and (
       category_slug is null
       or exists (
         select 1
           from fixer_categories fc
           join repair_categories rc on rc.id = fc.category_id
          where fc.fixer_id = f.id and lower(rc.slug) = lower(category_slug)
       )
     )
     and (
       search_query is null
       or btrim(search_query) = ''
       -- ilike beats trigram similarity for the prefix-ish queries people
       -- actually type ("acme", "north st"); the trgm index still serves it.
       or f.shop_name ilike '%' || btrim(search_query) || '%'
       or f.address   ilike '%' || btrim(search_query) || '%'
       or exists (
         select 1
           from fixer_categories fc
           join repair_categories rc on rc.id = fc.category_id
          where fc.fixer_id = f.id
            and rc.name ilike '%' || btrim(search_query) || '%'
       )
     )
   order by f.verified desc, f.rating_avg desc, f.rating_count desc
   limit least(greatest(result_limit, 1), 250);
$$;
