-- 008_blog_templates.sql
--
-- Written to be re-runnable. This file seeds the default template, so a stale
-- copy of it is not inert: applying it against an existing database — or a fresh
-- one after a reset — overwrites whatever the live template is with whatever is
-- written here. That is why every statement below is guarded and why the seeded
-- HTML is kept in step with production rather than left at its first draft.

create table if not exists public.blog_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  html_template text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Add foreign key to blog_posts
alter table public.blog_posts
  add column if not exists template_id uuid references public.blog_templates(id) on delete set null;

-- Enable RLS
alter table public.blog_templates enable row level security;

-- Policies. Dropped first: create policy has no `if not exists`, so without this
-- a second run fails here and never reaches the seed below.
drop policy if exists "Anyone can read blog templates" on public.blog_templates;
create policy "Anyone can read blog templates"
  on public.blog_templates for select
  using ( true );

drop policy if exists "Admins can insert blog templates" on public.blog_templates;
create policy "Admins can insert blog templates"
  on public.blog_templates for insert
  with check ( auth.role() = 'authenticated' );

drop policy if exists "Admins can update blog templates" on public.blog_templates;
create policy "Admins can update blog templates"
  on public.blog_templates for update
  using ( auth.role() = 'authenticated' );

drop policy if exists "Admins can delete blog templates" on public.blog_templates;
create policy "Admins can delete blog templates"
  on public.blog_templates for delete
  using ( auth.role() = 'authenticated' );

-- The default template.
--
-- The body is a bare `.blog-body` div, not a white card floated over the hero.
-- The card was the original design and it read as a dialog dropped on the page:
-- it boxed the prose at an unreadable width and fought the site's own surface
-- colours. `.blog-body` in `src/app/globals.css` sets a 68ch measure and inherits
-- the site typography, so the article reads as one continuous column under the
-- hero. Restoring the card here would silently undo that on the next apply.
--
-- Typography is deliberately NOT set with `prose-*` utilities. Those classes are
-- generated by scanning source files; Tailwind never sees this string, so any
-- prose variant written here produces no CSS at all and the post renders unstyled.
-- Everything visual for the body therefore lives in `globals.css`.
insert into public.blog_templates (id, name, html_template)
values (
  '11111111-1111-1111-1111-111111111111',
  'Modern Hero',
  '<article class="min-h-screen bg-wash pb-24">
  <header class="relative overflow-hidden bg-enamel pt-32 pb-32 px-4 text-center isolate">
    <div class="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-signal/20 via-enamel to-enamel"></div>
    <div class="absolute top-1/2 left-1/2 -z-10 h-[400px] w-[600px] -translate-x-1/2 -translate-y-1/2 opacity-30 blur-[100px] bg-gradient-to-tr from-signal to-blue-500 rounded-full mix-blend-screen"></div>

    <div class="mx-auto max-w-4xl">
      <a href="/" class="inline-flex items-center gap-2 mb-8 text-sm font-medium text-steel hover:text-white transition-colors duration-200">
        Back to Home
      </a>

      <h1 class="mb-8 text-4xl font-bold tracking-tight text-white md:text-5xl lg:text-6xl leading-tight" style="text-wrap: balance;">
        {{title}}
      </h1>

      <div class="flex items-center justify-center gap-3 text-steel">
        <time class="text-sm font-medium tracking-wide uppercase text-white/80">
          {{date}}
        </time>
      </div>
    </div>
  </header>

  <div class="blog-body">
    {{content}}
  </div>
</article>'
)
on conflict (id) do update
  set name = excluded.name,
      html_template = excluded.html_template,
      updated_at = now();

-- Give posts that have no template the default one.
--
-- `where template_id is null`, not a blanket update: an unqualified assignment
-- would reassign every post on a re-run and throw away any template an editor
-- had deliberately picked.
update public.blog_posts
  set template_id = '11111111-1111-1111-1111-111111111111'
  where template_id is null;
