/**
 * Row types for the booking marketplace — everything added by
 * `supabase/migrations/001_marketplace.sql`.
 *
 * Deliberately NOT in `database.ts`: that file carries a "regenerate in place"
 * header and is meant to be overwritten wholesale by
 * `supabase gen types typescript`. Anything hand-written there is lost on the
 * next run. These live here and are imported alongside it.
 *
 * Money is `integer` pence everywhere, matching the migration. No floats — a
 * price is a count of pence, and 19.99 is not representable in binary.
 */

import type { Json, Weekday } from "@/lib/types/database";

/* ── Enums, mirroring the Postgres types one-for-one ─────────────────────── */

/**
 * The booking lifecycle. The happy path is the first six, in order; the rest
 * are terminal branches off it. `src/lib/bookings/machine.ts` owns which
 * transitions are legal — this type only says what the values are.
 */
export type BookingStatus =
  | "requested"
  | "accepted"
  | "confirmed"
  | "in_progress"
  | "completed"
  | "closed"
  | "declined"
  | "cancelled_customer"
  | "cancelled_shop"
  | "no_show"
  | "expired"
  | "disputed";

export type DeliveryMode = "in_shop" | "home_visit" | "pickup_drop";
export type PriceType = "fixed" | "from" | "quote";
export type ClaimStatus = "pending" | "approved" | "rejected" | "withdrawn";
export type PaymentStatus =
  | "pending"
  | "authorized"
  | "captured"
  | "refunded"
  | "partially_refunded"
  | "failed";
export type PayoutStatus = "scheduled" | "in_transit" | "paid" | "failed";
export type DisputeStatus =
  | "open"
  | "awaiting_customer"
  | "awaiting_shop"
  | "under_review"
  | "resolved"
  | "withdrawn";
export type DisputeResolution =
  | "refund_full"
  | "refund_partial"
  | "redo_service"
  | "no_action";
export type ContactMethod = "email" | "phone" | "sms";
export type NotificationKind =
  | "booking_requested"
  | "booking_accepted"
  | "booking_declined"
  | "booking_confirmed"
  | "booking_reminder"
  | "booking_started"
  | "booking_completed"
  | "booking_cancelled"
  | "booking_rescheduled"
  | "message_received"
  | "review_request"
  | "warranty_expiring"
  | "dispute_opened"
  | "dispute_updated"
  | "dispute_resolved"
  | "payout_sent"
  | "claim_reviewed";

/** Actor on a booking transition. `system` covers the cron expiry jobs. */
export type ActorRole = "customer" | "shop" | "system" | "admin";

/** What a booking attachment is a photo of. */
export type AttachmentKind = "fault" | "completion" | "evidence";

/* ── Human labels ─────────────────────────────────────────────────────────── */

export const BOOKING_STATUS_LABELS: Record<BookingStatus, string> = {
  requested: "Requested",
  accepted: "Quote ready",
  confirmed: "Confirmed",
  in_progress: "In progress",
  completed: "Completed",
  closed: "Closed",
  declined: "Declined",
  cancelled_customer: "Cancelled by you",
  cancelled_shop: "Cancelled by shop",
  no_show: "No show",
  expired: "Expired",
  disputed: "In dispute",
};

export const DELIVERY_MODE_LABELS: Record<DeliveryMode, string> = {
  in_shop: "Drop in to the shop",
  home_visit: "Home visit",
  pickup_drop: "Collection and return",
};

/** Statuses where the job is live and the customer should be kept informed. */
export const ACTIVE_BOOKING_STATUSES: readonly BookingStatus[] = [
  "requested",
  "accepted",
  "confirmed",
  "in_progress",
];

/** Statuses where nothing further happens unless a dispute is raised. */
export const CLOSED_BOOKING_STATUSES: readonly BookingStatus[] = [
  "closed",
  "declined",
  "cancelled_customer",
  "cancelled_shop",
  "no_show",
  "expired",
];

/* ── Rows ─────────────────────────────────────────────────────────────────── */

export interface ShopClaimRow {
  id: string;
  fixer_id: string;
  user_id: string;
  status: ClaimStatus;
  evidence: string | null;
  contact_phone: string | null;
  /** `seo_admins.id`. No FK — that table lives on the admin side. */
  reviewed_by: string | null;
  reviewed_at: string | null;
  review_note: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * A message from the platform to one shop owner.
 *
 * Distinct from `NotificationRow`: those are generated by product events and
 * read casually, whereas a notice is written by a person and must be
 * acknowledged. `sent_by` names a `seo_admins` row with no foreign key — that
 * table belongs to the admin app, and deleting an admin must not delete the
 * notices they sent.
 */
export interface ShopNoticeRow {
  id: string;
  fixer_id: string;
  sent_by: string | null;
  subject: string;
  body: string;
  severity: "info" | "warning" | "urgent";
  acknowledged_at: string | null;
  created_at: string;
}

export interface UserAddressRow {
  id: string;
  user_id: string;
  label: string | null;
  line1: string;
  line2: string | null;
  city: string | null;
  postcode: string | null;
  country: string;
  lat: number | null;
  lng: number | null;
  is_default: boolean;
  created_at: string;
}

export interface ShopServiceRow {
  id: string;
  fixer_id: string;
  category_id: string | null;
  name: string;
  description: string | null;
  price_type: PriceType;
  /** Pence. */
  price_min: number | null;
  /** Pence. */
  price_max: number | null;
  currency: string;
  duration_minutes: number;
  delivery_modes: DeliveryMode[];
  warranty_days: number;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface ShopAvailabilityRow {
  id: string;
  fixer_id: string;
  weekday: Weekday;
  /** `HH:MM:SS`, in the shop's own timezone. */
  starts_at: string;
  ends_at: string;
  buffer_minutes: number;
  capacity: number;
  created_at: string;
}

export interface ShopTimeOffRow {
  id: string;
  fixer_id: string;
  /** Postgres `tstzrange`, serialised by PostgREST as `["2026-08-01T…","2026-08-08T…")`. */
  period: string;
  reason: string | null;
  created_at: string;
}

export interface BookingRow {
  id: string;
  /** Human-facing, e.g. `FIX-7Q2M4X`. Generated by a trigger, never by the app. */
  reference: string;
  customer_id: string;
  fixer_id: string;
  service_id: string | null;
  status: BookingStatus;
  delivery_mode: DeliveryMode;
  /** `tstzrange` text form. Use `parseRange` in `src/lib/bookings/range.ts`. */
  slot: string;

  device_details: string | null;
  customer_notes: string | null;

  address_line1: string | null;
  address_line2: string | null;
  address_city: string | null;
  address_postcode: string | null;
  address_lat: number | null;
  address_lng: number | null;

  /** Pence. */
  quoted_amount: number | null;
  /** Pence. */
  final_amount: number | null;
  platform_fee: number;
  tax_amount: number;
  currency: string;

  warranty_days: number;
  warranty_expires_at: string | null;

  requested_at: string;
  responded_at: string | null;
  confirmed_at: string | null;
  started_at: string | null;
  completed_at: string | null;
  closed_at: string | null;
  cancelled_at: string | null;
  cancelled_by: string | null;
  cancellation_reason: string | null;

  expires_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface BookingEventRow {
  id: string;
  booking_id: string;
  /** Null for system actions — cron expiry, warranty close. */
  actor_id: string | null;
  actor_role: ActorRole | null;
  from_status: BookingStatus | null;
  to_status: BookingStatus | null;
  note: string | null;
  metadata: Json;
  created_at: string;
}

export interface BookingAttachmentRow {
  id: string;
  booking_id: string;
  uploaded_by: string;
  /** Path inside the private bucket, not a URL. Render via a signed URL. */
  storage_path: string;
  file_name: string | null;
  mime_type: string | null;
  size_bytes: number | null;
  kind: AttachmentKind;
  created_at: string;
}

export interface SavedExpertRow {
  user_id: string;
  fixer_id: string;
  created_at: string;
}

export interface MessageThreadRow {
  id: string;
  booking_id: string;
  customer_id: string;
  fixer_id: string;
  last_message_at: string | null;
  created_at: string;
}

export interface MessageRow {
  id: string;
  thread_id: string;
  sender_id: string;
  body: string;
  read_at: string | null;
  created_at: string;
}

export interface MessageAttachmentRow {
  id: string;
  message_id: string;
  storage_path: string;
  file_name: string | null;
  mime_type: string | null;
  size_bytes: number | null;
  created_at: string;
}

export interface NotificationRow {
  id: string;
  user_id: string;
  kind: NotificationKind;
  title: string;
  body: string | null;
  href: string | null;
  booking_id: string | null;
  read_at: string | null;
  email_sent_at: string | null;
  created_at: string;
}

export interface NotificationPrefsRow {
  user_id: string;
  email_bookings: boolean;
  email_messages: boolean;
  email_reminders: boolean;
  email_marketing: boolean;
  sms_reminders: boolean;
  created_at: string;
  updated_at: string;
}

export interface PaymentRow {
  id: string;
  booking_id: string;
  customer_id: string;
  status: PaymentStatus;
  /** Pence, gross. */
  amount: number;
  platform_fee: number;
  tax_amount: number;
  currency: string;
  provider: string;
  provider_intent_id: string | null;
  provider_charge_id: string | null;
  authorized_at: string | null;
  captured_at: string | null;
  failed_at: string | null;
  failure_reason: string | null;
  created_at: string;
  updated_at: string;
}

export interface RefundRow {
  id: string;
  payment_id: string;
  booking_id: string;
  /** Pence. */
  amount: number;
  reason: string | null;
  provider_refund_id: string | null;
  created_by: string | null;
  created_at: string;
}

export interface PayoutRow {
  id: string;
  fixer_id: string;
  status: PayoutStatus;
  /** Pence, net of the platform fee. */
  amount: number;
  currency: string;
  provider_payout_id: string | null;
  scheduled_for: string | null;
  paid_at: string | null;
  created_at: string;
}

export type LedgerKind = "charge" | "fee" | "refund" | "payout" | "adjustment";

export interface LedgerEntryRow {
  id: string;
  booking_id: string | null;
  payment_id: string | null;
  payout_id: string | null;
  fixer_id: string | null;
  customer_id: string | null;
  kind: LedgerKind;
  /** Pence, signed. */
  amount: number;
  currency: string;
  memo: string | null;
  created_at: string;
}

export interface DisputeRow {
  id: string;
  booking_id: string;
  raised_by: string;
  status: DisputeStatus;
  reason: string;
  desired_outcome: string | null;
  resolution: DisputeResolution | null;
  resolution_note: string | null;
  /** Pence, when the resolution refunds. */
  refund_amount: number | null;
  resolved_by: string | null;
  resolved_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface DisputeMessageRow {
  id: string;
  dispute_id: string;
  author_id: string | null;
  author_role: "customer" | "shop" | "admin";
  body: string;
  created_at: string;
}

export interface DisputeEvidenceRow {
  id: string;
  dispute_id: string;
  uploaded_by: string;
  storage_path: string;
  file_name: string | null;
  mime_type: string | null;
  size_bytes: number | null;
  created_at: string;
}

/**
 * The shop's private working notes on one job.
 *
 * A table rather than a column on `bookings` because RLS is row-level: a
 * customer allowed to read their own booking row can read every column of it,
 * so no column of `bookings` can ever be shop-private. Owner-only policy in
 * `supabase/policies-marketplace.sql`.
 */
export interface BookingNoteRow {
  booking_id: string;
  fixer_id: string;
  body: string;
  updated_by: string | null;
  updated_at: string;
  created_at: string;
}

export interface ClientNoteRow {
  id: string;
  fixer_id: string;
  customer_id: string;
  body: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

/* ── Columns added to existing tables by phase 3 ──────────────────────────── */

/** `users`, after the migration widens it from four columns to a real profile. */
export interface UserProfileRow {
  id: string;
  display_name: string;
  avatar_url: string | null;
  full_name: string | null;
  phone: string | null;
  phone_verified: boolean;
  timezone: string;
  preferred_contact: ContactMethod;
  marketing_opt_in: boolean;
  onboarded_at: string | null;
  created_at: string;
  updated_at: string;
}

/** Booking-related columns added to `fixer_profiles`. */
export interface FixerBookingSettings {
  accepts_bookings: boolean;
  /** Minimum notice, in hours, before the first bookable slot. */
  booking_lead_hours: number;
  /** How far ahead the calendar is open, in days. */
  booking_horizon_days: number;
  auto_accept: boolean;
  /** Advertised response time, in hours. */
  response_hours: number;
  default_warranty_days: number;
  payout_email: string | null;
  stripe_account_id: string | null;
}

/* ── Joined shapes the dashboards actually render ─────────────────────────── */

/** The shop fields a customer-facing booking card needs. */
export interface BookingShopSummary {
  id: string;
  slug: string;
  shop_name: string;
  address: string;
  timezone: string;
  verified: boolean;
  contact_phone: string | null;
  rating_avg: number;
  rating_count: number;
}

/** The customer fields an expert-facing booking card needs. */
export interface BookingCustomerSummary {
  id: string;
  display_name: string;
  full_name: string | null;
  avatar_url: string | null;
  phone: string | null;
}

/** A booking with everything the dashboard lists need, in one row. */
export interface BookingWithParties extends BookingRow {
  shop: BookingShopSummary | null;
  customer: BookingCustomerSummary | null;
  service: Pick<ShopServiceRow, "id" | "name" | "duration_minutes"> | null;
}
